export const PHONE_CODES: Array<{ code: string; label: string }> = [
  { code: '+1', label: 'United States (+1)' },
  { code: '+7', label: 'Russia (+7)' },
  { code: '+20', label: 'Egypt (+20)' },
  { code: '+27', label: 'South Africa (+27)' },
  { code: '+30', label: 'Greece (+30)' },
  { code: '+31', label: 'Netherlands (+31)' },
  { code: '+32', label: 'Belgium (+32)' },
  { code: '+33', label: 'France (+33)' },
  { code: '+34', label: 'Spain (+34)' },
  { code: '+36', label: 'Hungary (+36)' },
  { code: '+39', label: 'Italy (+39)' },
  { code: '+40', label: 'Romania (+40)' },
  { code: '+41', label: 'Switzerland (+41)' },
  { code: '+43', label: 'Austria (+43)' },
  { code: '+44', label: 'United Kingdom (+44)' },
  { code: '+45', label: 'Denmark (+45)' },
  { code: '+46', label: 'Sweden (+46)' },
  { code: '+47', label: 'Norway (+47)' },
  { code: '+48', label: 'Poland (+48)' },
  { code: '+49', label: 'Germany (+49)' },
  { code: '+51', label: 'Peru (+51)' },
  { code: '+52', label: 'Mexico (+52)' },
  { code: '+53', label: 'Cuba (+53)' },
  { code: '+54', label: 'Argentina (+54)' },
  { code: '+55', label: 'Brazil (+55)' },
  { code: '+56', label: 'Chile (+56)' },
  { code: '+57', label: 'Colombia (+57)' },
  { code: '+58', label: 'Venezuela (+58)' },
  { code: '+60', label: 'Malaysia (+60)' },
  { code: '+61', label: 'Australia (+61)' },
  { code: '+62', label: 'Indonesia (+62)' },
  { code: '+63', label: 'Philippines (+63)' },
  { code: '+64', label: 'New Zealand (+64)' },
  { code: '+65', label: 'Singapore (+65)' },
  { code: '+66', label: 'Thailand (+66)' },
  { code: '+81', label: 'Japan (+81)' },
  { code: '+82', label: 'South Korea (+82)' },
  { code: '+84', label: 'Vietnam (+84)' },
  { code: '+86', label: 'China (+86)' },
  { code: '+90', label: 'Turkey (+90)' },
  { code: '+91', label: 'India (+91)' },
  { code: '+92', label: 'Pakistan (+92)' },
  { code: '+93', label: 'Afghanistan (+93)' },
  { code: '+94', label: 'Sri Lanka (+94)' },
  { code: '+95', label: 'Myanmar (+95)' },
  { code: '+98', label: 'Iran (+98)' },
  { code: '+212', label: 'Morocco (+212)' },
  { code: '+213', label: 'Algeria (+213)' },
  { code: '+216', label: 'Tunisia (+216)' },
  { code: '+218', label: 'Libya (+218)' },
  { code: '+220', label: 'Gambia (+220)' },
  { code: '+221', label: 'Senegal (+221)' },
  { code: '+233', label: 'Ghana (+233)' },
  { code: '+234', label: 'Nigeria (+234)' },
  { code: '+249', label: 'Sudan (+249)' },
  { code: '+251', label: 'Ethiopia (+251)' },
  { code: '+254', label: 'Kenya (+254)' },
  { code: '+255', label: 'Tanzania (+255)' },
  { code: '+256', label: 'Uganda (+256)' },
  { code: '+260', label: 'Zambia (+260)' },
  { code: '+263', label: 'Zimbabwe (+263)' },
  { code: '+380', label: 'Ukraine (+380)' },
  { code: '+420', label: 'Czech Republic (+420)' },
  { code: '+886', label: 'Taiwan (+886)' },
  { code: '+961', label: 'Lebanon (+961)' },
  { code: '+962', label: 'Jordan (+962)' },
  { code: '+963', label: 'Syria (+963)' },
  { code: '+964', label: 'Iraq (+964)' },
  { code: '+965', label: 'Kuwait (+965)' },
  { code: '+966', label: 'Saudi Arabia (+966)' },
  { code: '+967', label: 'Yemen (+967)' },
  { code: '+968', label: 'Oman (+968)' },
  { code: '+970', label: 'Palestine (+970)' },
  { code: '+971', label: 'UAE (+971)' },
  { code: '+972', label: 'Israel (+972)' },
  { code: '+973', label: 'Bahrain (+973)' },
  { code: '+974', label: 'Qatar (+974)' },
  { code: '+975', label: 'Bhutan (+975)' },
  { code: '+976', label: 'Mongolia (+976)' },
  { code: '+998', label: 'Uzbekistan (+998)' },
];

export const NATIONALITIES: string[] = [
  'Afghan','Albanian','Algerian','American','Andorran','Angolan','Argentine','Armenian','Australian','Austrian','Azerbaijani',
  'Bahraini','Bangladeshi','Belgian','Bolivian','Bosnian','Botswanan','Brazilian','British','Bulgarian',
  'Cambodian','Cameroonian','Canadian','Chilean','Chinese','Colombian','Croatian','Cuban','Cypriot','Czech',
  'Danish','Dominican','Dutch','Ecuadorian','Egyptian','Emirati','English','Ethiopian','Finnish','French','Georgian','German','Ghanaian','Greek','Guatemalan',
  'Hungarian','Icelandic','Indian','Indonesian','Iranian','Iraqi','Irish','Italian','Jamaican','Japanese','Jordanian','Kazakh','Kenyan','Kuwaiti',
  'Lebanese','Libyan','Lithuanian','Luxembourger','Malaysian','Maltese','Mexican','Moroccan','Nepalese','New Zealander','Nigerian','Norwegian','Omani',
  'Pakistani','Palestinian','Peruvian','Philippine','Polish','Portuguese','Qatari','Romanian','Russian','Saudi','Scottish','Serbian','Singaporean','Slovak',
  'Slovenian','South African','South Korean','Spanish','Sri Lankan','Sudanese','Swedish','Swiss','Syrian','Taiwanese','Tanzanian','Thai','Tunisian','Turkish',
  'Ukrainian','Uruguayan','Uzbek','Venezuelan','Vietnamese','Welsh','Yemeni','Zimbabwean'
];
